"""Initial migration

Revision ID: 21d39feca545
Revises: 
Create Date: 2025-12-06 08:51:53.890607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21d39feca545'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('heure_debut_travail', sa.Time(), nullable=True),
    sa.Column('heure_fin_travail', sa.Time(), nullable=True),
    sa.Column('jours_interdits', sa.String(), nullable=True),
    sa.Column('tolerance_gps_metres', sa.Integer(), nullable=True),
    sa.Column('message_du_jour', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questionnaire_uuid', sa.String(), nullable=False),
    sa.Column('agent_code', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('complet', 'partiel', 'refus', name='surveystatus'), nullable=True),
    sa.Column('respondent_sex', sa.Enum('M', 'F', 'Inconnu', name='genderenum'), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('date_entretien', sa.DateTime(), nullable=True),
    sa.Column('date_synchro', sa.DateTime(), nullable=True),
    sa.Column('duree_minutes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_data_agent_code'), 'survey_data', ['agent_code'], unique=False)
    op.create_index(op.f('ix_survey_data_id'), 'survey_data', ['id'], unique=False)
    op.create_index(op.f('ix_survey_data_questionnaire_uuid'), 'survey_data', ['questionnaire_uuid'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('directeur', 'superviseur', 'controleur', 'agent', name='roleenum'), nullable=False),
    sa.Column('cspro_code', sa.String(), nullable=True),
    sa.Column('chef_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chef_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_cspro_code'), 'users', ['cspro_code'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_zone', sa.String(), nullable=False),
    sa.Column('latitude_centrale', sa.Float(), nullable=False),
    sa.Column('longitude_centrale', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zones_id'), 'zones', ['id'], unique=False)
    op.create_index(op.f('ix_zones_nom_zone'), 'zones', ['nom_zone'], unique=False)
    op.create_table('affectations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('controleur_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('quota_attendu', sa.Integer(), nullable=True),
    sa.Column('date_debut', sa.DateTime(), nullable=True),
    sa.Column('date_fin', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['controleur_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affectations_id'), 'affectations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_affectations_id'), table_name='affectations')
    op.drop_table('affectations')
    op.drop_index(op.f('ix_zones_nom_zone'), table_name='zones')
    op.drop_index(op.f('ix_zones_id'), table_name='zones')
    op.drop_table('zones')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_cspro_code'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_survey_data_questionnaire_uuid'), table_name='survey_data')
    op.drop_index(op.f('ix_survey_data_id'), table_name='survey_data')
    op.drop_index(op.f('ix_survey_data_agent_code'), table_name='survey_data')
    op.drop_table('survey_data')
    op.drop_table('global_settings')
    # ### end Alembic commands ###
