"""Add ID mapping fields

Revision ID: 3d4bdc13fb33
Revises: dfabda1796d4
Create Date: 2026-01-30 12:27:33.994077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d4bdc13fb33'
down_revision: Union[str, Sequence[str], None] = 'dfabda1796d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_settings', sa.Column('variable_id_interne', sa.String(), nullable=True, comment='Nom de la colonne UUID (ex: questionnaire_uuid)'))
    op.add_column('global_settings', sa.Column('variable_code_agent', sa.String(), nullable=True, comment='Nom de la colonne Code Agent (ex: agent_id)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('global_settings', 'variable_code_agent')
    op.drop_column('global_settings', 'variable_id_interne')
    # ### end Alembic commands ###
