"""add source_column to variable

Revision ID: 684e78f11427
Revises: b027e3d10b40
Create Date: 2026-02-06 09:58:59.046973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '684e78f11427'
down_revision: Union[str, Sequence[str], None] = 'b027e3d10b40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variables', sa.Column('source_column', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('variables', 'source_column')
    # ### end Alembic commands ###
