"""empty message

Revision ID: 8c45088dd36d
Revises: e1ab31a36267
Create Date: 2026-01-24 07:15:49.878973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c45088dd36d'
down_revision: Union[str, Sequence[str], None] = 'e1ab31a36267'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotas_id'), 'quotas', ['id'], unique=False)
    op.create_table('user_quotas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quota_id', sa.Integer(), nullable=False),
    sa.Column('effectif_cible', sa.Integer(), nullable=False),
    sa.Column('effectif_actuel', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['quota_id'], ['quotas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_quotas_id'), 'user_quotas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_quotas_id'), table_name='user_quotas')
    op.drop_table('user_quotas')
    op.drop_index(op.f('ix_quotas_id'), table_name='quotas')
    op.drop_table('quotas')
    # ### end Alembic commands ###
