"""ajout module dictionnaire variables

Revision ID: a029ced4af64
Revises: cb93fc141ae2
Create Date: 2025-12-16 22:21:00.341439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a029ced4af64'
down_revision: Union[str, Sequence[str], None] = 'cb93fc141ae2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('variables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('choix_unique', 'choix_multiple', 'entier', 'texte', name='variabletype'), nullable=True),
    sa.Column('est_quota', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variables_id'), 'variables', ['id'], unique=False)
    op.create_index(op.f('ix_variables_name'), 'variables', ['name'], unique=True)
    op.create_table('modalites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variable_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['variable_id'], ['variables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modalites_id'), 'modalites', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_modalites_id'), table_name='modalites')
    op.drop_table('modalites')
    op.drop_index(op.f('ix_variables_name'), table_name='variables')
    op.drop_index(op.f('ix_variables_id'), table_name='variables')
    op.drop_table('variables')
    # ### end Alembic commands ###
