"""remove respondent_sex

Revision ID: b027e3d10b40
Revises: b8edd5d39835
Create Date: 2026-02-06 09:18:10.074155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b027e3d10b40'
down_revision: Union[str, Sequence[str], None] = 'b8edd5d39835'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey_data', 'respondent_sex')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_data', sa.Column('respondent_sex', postgresql.ENUM('M', 'F', 'Inconnu', name='genderenum'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
