"""ajout tables zones et affectations

Revision ID: b7fb4fcae03d
Revises: b7709afc2d77
Create Date: 2025-12-16 05:54:21.790566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7fb4fcae03d'
down_revision: Union[str, Sequence[str], None] = 'b7709afc2d77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('affectations', sa.Column('est_actif', sa.Boolean(), nullable=True))
    op.add_column('affectations', sa.Column('objectifs_quota', sa.JSON(), nullable=True))
    op.add_column('zones', sa.Column('rayon_tolerance_metres', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zones', 'rayon_tolerance_metres')
    op.drop_column('affectations', 'objectifs_quota')
    op.drop_column('affectations', 'est_actif')
    # ### end Alembic commands ###
