"""ajout module dictionnaire variables

Revision ID: b8b6366d0e6b
Revises: cb93fc141ae2
Create Date: 2025-12-16 19:36:37.212120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8b6366d0e6b'
down_revision: Union[str, Sequence[str], None] = 'cb93fc141ae2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
