"""add_unique_constraint_to_affectations

Revision ID: b8edd5d39835
Revises: 1161858c1eab
Create Date: 2026-02-03 10:00:58.846928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8edd5d39835'
down_revision: Union[str, Sequence[str], None] = '1161858c1eab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_controleur_zone', 'affectations', ['controleur_id', 'zone_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_controleur_zone', 'affectations', type_='unique')
    # ### end Alembic commands ###
