"""ajout table global_settings pour contrôle qualité

Revision ID: cb93fc141ae2
Revises: b7fb4fcae03d
Create Date: 2025-12-16 17:06:53.411529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb93fc141ae2'
down_revision: Union[str, Sequence[str], None] = 'b7fb4fcae03d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_settings', sa.Column('check_heure', sa.Boolean(), nullable=True))
    op.add_column('global_settings', sa.Column('check_jours', sa.Boolean(), nullable=True))
    op.add_column('global_settings', sa.Column('check_gps', sa.Boolean(), nullable=True))
    op.add_column('global_settings', sa.Column('check_duree', sa.Boolean(), nullable=True))
    op.add_column('global_settings', sa.Column('min_duree_minutes', sa.Integer(), nullable=True))
    op.add_column('global_settings', sa.Column('check_vitesse', sa.Boolean(), nullable=True))
    op.add_column('global_settings', sa.Column('max_enquetes_par_jour', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('global_settings', 'max_enquetes_par_jour')
    op.drop_column('global_settings', 'check_vitesse')
    op.drop_column('global_settings', 'min_duree_minutes')
    op.drop_column('global_settings', 'check_duree')
    op.drop_column('global_settings', 'check_gps')
    op.drop_column('global_settings', 'check_jours')
    op.drop_column('global_settings', 'check_heure')
    # ### end Alembic commands ###
