"""Refactor dictionary models to slug and json

Revision ID: cf18f74d93c5
Revises: a029ced4af64
Create Date: 2026-01-24 06:39:29.360214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf18f74d93c5'
down_revision: Union[str, Sequence[str], None] = 'a029ced4af64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modalites', sa.Column('value', sa.String(), nullable=False))
    op.add_column('modalites', sa.Column('order', sa.Integer(), nullable=True))
    op.drop_column('modalites', 'code')
    op.add_column('variables', sa.Column('slug', sa.String(), nullable=False))
    op.add_column('variables', sa.Column('data_type', sa.String(), nullable=False))
    op.add_column('variables', sa.Column('ui_config', sa.JSON(), nullable=True))
    op.add_column('variables', sa.Column('excluded_operators', sa.JSON(), nullable=True))
    op.add_column('variables', sa.Column('is_quota', sa.Boolean(), nullable=True))
    op.drop_index(op.f('ix_variables_name'), table_name='variables')
    op.create_index(op.f('ix_variables_is_quota'), 'variables', ['is_quota'], unique=False)
    op.create_index(op.f('ix_variables_slug'), 'variables', ['slug'], unique=True)
    op.drop_column('variables', 'name')
    op.drop_column('variables', 'est_quota')
    op.drop_column('variables', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variables', sa.Column('type', postgresql.ENUM('choix_unique', 'choix_multiple', 'entier', 'texte', name='variabletype'), autoincrement=False, nullable=True))
    op.add_column('variables', sa.Column('est_quota', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('variables', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_variables_slug'), table_name='variables')
    op.drop_index(op.f('ix_variables_is_quota'), table_name='variables')
    op.create_index(op.f('ix_variables_name'), 'variables', ['name'], unique=True)
    op.drop_column('variables', 'is_quota')
    op.drop_column('variables', 'excluded_operators')
    op.drop_column('variables', 'ui_config')
    op.drop_column('variables', 'data_type')
    op.drop_column('variables', 'slug')
    op.add_column('modalites', sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('modalites', 'order')
    op.drop_column('modalites', 'value')
    # ### end Alembic commands ###
