"""Add partial logic fields

Revision ID: dfabda1796d4
Revises: ebb6214230e2
Create Date: 2026-01-30 11:36:58.772528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfabda1796d4'
down_revision: Union[str, Sequence[str], None] = 'ebb6214230e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_settings', sa.Column('variable_indicateur_partiel', sa.String(), nullable=True, comment="Variable indiquant si l'entretien est partiel/incomplet (ex: SS_STATUS)"))
    op.add_column('global_settings', sa.Column('valeur_partiel', sa.String(), nullable=True, comment="Valeur qui signifie 'Partiel' (ex: '1' ou 'Partial')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('global_settings', 'valeur_partiel')
    op.drop_column('global_settings', 'variable_indicateur_partiel')
    # ### end Alembic commands ###
