"""Add target_table_name to settings

Revision ID: ebb6214230e2
Revises: 8c45088dd36d
Create Date: 2026-01-30 10:57:07.953763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebb6214230e2'
down_revision: Union[str, Sequence[str], None] = '8c45088dd36d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_settings', sa.Column('variable_duree_start', sa.String(), nullable=True))
    op.add_column('global_settings', sa.Column('variable_duree_end', sa.String(), nullable=True))
    op.add_column('global_settings', sa.Column('variable_gps_lat', sa.String(), nullable=True))
    op.add_column('global_settings', sa.Column('variable_gps_lon', sa.String(), nullable=True))
    op.add_column('global_settings', sa.Column('variable_date_enquete', sa.String(), nullable=True))
    op.add_column('global_settings', sa.Column('target_table_name', sa.String(), nullable=True, comment='Nom de la table MySQL source (ex: 2024, 2025)'))
    op.add_column('global_settings', sa.Column('variable_heure_enquete', sa.String(), nullable=True))
    op.add_column('survey_data', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('survey_data', sa.Column('is_valid', sa.Boolean(), nullable=True))
    op.add_column('survey_data', sa.Column('qc_results', sa.JSON(), nullable=True))
    op.add_column('survey_data', sa.Column('answers', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'survey_data', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'survey_data', type_='foreignkey')
    # ### end Alembic commands ###
