"""Add target_table_name to settings

Revision ID: ebb6214230e2
Revises: 8c45088dd36d
Create Date: 2026-01-30 10:57:07.953763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebb6214230e2'
down_revision: Union[str, Sequence[str], None] = '8c45088dd36d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('variables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('data_type', sa.String(), nullable=False),
    sa.Column('ui_config', sa.JSON(), nullable=True),
    sa.Column('excluded_operators', sa.JSON(), nullable=True),
    sa.Column('is_quota', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variables_id'), 'variables', ['id'], unique=False)
    op.create_index(op.f('ix_variables_is_quota'), 'variables', ['is_quota'], unique=False)
    op.create_index(op.f('ix_variables_slug'), 'variables', ['slug'], unique=True)
    op.create_table('modalites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variable_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['variable_id'], ['variables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modalites_id'), 'modalites', ['id'], unique=False)
    op.add_column('global_settings', sa.Column('variable_duree_start', sa.String(), nullable=True))
    op.add_column('global_settings', sa.Column('variable_duree_end', sa.String(), nullable=True))
    op.add_column('global_settings', sa.Column('variable_gps_lat', sa.String(), nullable=True))
    op.add_column('global_settings', sa.Column('variable_gps_lon', sa.String(), nullable=True))
    op.add_column('global_settings', sa.Column('variable_date_enquete', sa.String(), nullable=True))
    op.add_column('global_settings', sa.Column('target_table_name', sa.String(), nullable=True, comment='Nom de la table MySQL source (ex: 2024, 2025)'))
    op.add_column('global_settings', sa.Column('variable_heure_enquete', sa.String(), nullable=True))
    op.add_column('survey_data', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('survey_data', sa.Column('is_valid', sa.Boolean(), nullable=True))
    op.add_column('survey_data', sa.Column('qc_results', sa.JSON(), nullable=True))
    op.add_column('survey_data', sa.Column('answers', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'survey_data', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'survey_data', type_='foreignkey')
    op.drop_column('survey_data', 'answers')
    op.drop_column('survey_data', 'qc_results')
    op.drop_column('survey_data', 'is_valid')
    op.drop_column('survey_data', 'user_id')
    op.drop_column('global_settings', 'variable_heure_enquete')
    op.drop_column('global_settings', 'target_table_name')
    op.drop_column('global_settings', 'variable_date_enquete')
    op.drop_column('global_settings', 'variable_gps_lon')
    op.drop_column('global_settings', 'variable_gps_lat')
    op.drop_column('global_settings', 'variable_duree_end')
    op.drop_column('global_settings', 'variable_duree_start')
    op.drop_index(op.f('ix_modalites_id'), table_name='modalites')
    op.drop_table('modalites')
    op.drop_index(op.f('ix_variables_slug'), table_name='variables')
    op.drop_index(op.f('ix_variables_is_quota'), table_name='variables')
    op.drop_index(op.f('ix_variables_id'), table_name='variables')
    op.drop_table('variables')
    # ### end Alembic commands ###
